spring:
  datasource:
    url: jdbc:mysql://climbing-friends-db.c6wfr5mnao1k.ap-northeast-2.rds.amazonaws.com:3306/climbing?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: climber
    password: zmfclsdoq77

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true

